apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: backend
data:
  application.yml: |
    server:
      port: 8181

    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          mvc:
            routes:
              - id: user-service
                uri: http://user-service:8081
                predicates:
                  - Path=/api/users/**
                filters:
                  - StripPrefix=0

              - id: security-service
                uri: http://security-service:8085
                predicates:
                  - Path=/api/security/auth/**
                filters:
                  - StripPrefix=0

    eureka:
      client:
        serviceUrl:
          defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# https://github.com/kemanedonfack/springboot-microservices-deployment-kubernetes-helm-gitlabci/tree/main/ecommerce-api-gateway