apiVersion: v1
data:
  application.yml: |-
    server:
      port: 8080

    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          routes:
            - id: user-service
              uri: http://user-service:8081
              predicates:
                - Path=/api/users/**
              filters:
                - name: RewritePath
                  args:
                    regexp: '/api/users/(?<segment>.*)'
                    replacement: /${segment}

            - id: security-service
              uri: http://security-service:8085
              predicates:
                - Path=/auth/**
              filters:
                - name: RewritePath
                  args:
                    regexp: '/auth/(?<segment>.*)'
                    replacement: /${segment}

            - id: jwt-authentication-swagger
              uri: http://security-service:8085
              predicates:
                - Path=/api/v1/security/auth/swagger-ui/**
                - Path=/api/v1/security/auth/v3/api-docs/**
              filters:
                - name: RewritePath
                  args:
                    regexp: '/api/v1/security/auth/(?<segment>.*)'
                    replacement: /${segment}

            - id: security-service-actuator
              uri: http://security-service:8085
              predicates:
                - Path=/api/v1/security/auth/actuator/**
                - Path=/api/v1/security/auth/actuator/prometheus
              filters:
                - name: RewritePath
                  args:
                    regexp: '/api/v1/security/auth/actuator/(?<segment>.*)'
                    replacement: /actuator/${segment}

    logging:
      level:
        org.springframework.cloud.gateway: DEBUG
        org.springframework.web.reactive: DEBUG
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: backend
