apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
#          env:
#            - name: EUREKA_SERVER_URL
#              value: "http://discovery-server:8761/eureka/"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/application.yml
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: gateway-config

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: backend
spec:
  type: LoadBalancer  # Or ClusterIP if using Ingress
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP